---
version: "3.9"
services:
  jenkins:
    image: fortinetdemo/jenkins:jcasc
    volumes:
      - jenkins_home:/var/jenkins_home
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_ID=XXXXX
      - JENKINS_ADMIN=admin
      - JENKINS_ADMIN_PASSWORD=XXXXX
    ports:
      - 8080:8080
      - 50000:50000

volumes:
  jenkins_home:
