apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-minikube
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-minikube 
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-minikube
        image: k8s.gcr.io/echoserver:1.10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-minikube
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-minikube
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31133
